Listen 4500

<VirtualHost *:4500>

    ServerAdmin admin@localhost
    DocumentRoot /var/www/game

    <Directory /var/www/game>
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/game_error.log
    CustomLog ${APACHE_LOG_DIR}/game_access.log combined

</VirtualHost>
